/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package bocaditos;

import grafos.Grafo;
import java.awt.event.ItemEvent;
import java.util.LinkedList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author juangocc
 */
public class VentanaPrincipalBocadito extends javax.swing.JFrame {

    MapaCiudad mapaCiudad;
    Thread hiloJuego;
    boolean jugando;
    Almacen almacen;

    /**
     * Creates new form VentanaPrincipal
     */
    public VentanaPrincipalBocadito() {
        initComponents();
        mapaCiudad = new MapaCiudad();
        areaDeDibujo1.setMapaCiudad(mapaCiudad);
        jugando = true;
        iniciarJuego();
    }

    public void iniciarJuego() {
        hiloJuego = new Thread(new Runnable() {
            @Override
            public void run() {
                while (jugando) {
                    mapaCiudad.desplazarCamiones();
                    areaDeDibujo1.repaint();
                    try {
                        Thread.sleep(100);
                    } catch (InterruptedException ex) {
                        Logger.getLogger(VentanaPrincipalBocadito.class.getName()).log(Level.SEVERE, null, ex);
                    }
                }
            }
        });
        hiloJuego.start();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        areaDeDibujo1 = new bocaditos.AreaDeDibujo();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jBCrearVia = new javax.swing.JButton();
        jCBInterseccionInicial = new javax.swing.JComboBox();
        jCBInterseccionFinal = new javax.swing.JComboBox();
        jLabel3 = new javax.swing.JLabel();
        jCBCrearAlClick = new javax.swing.JComboBox();
        jLabel4 = new javax.swing.JLabel();
        jCBCasas = new javax.swing.JComboBox();
        jBHacerPedido = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jCBVias = new javax.swing.JComboBox();
        jLabel6 = new javax.swing.JLabel();
        jCBSentido = new javax.swing.JComboBox();
        jLabel7 = new javax.swing.JLabel();
        jCBPuesto = new javax.swing.JComboBox();
        jLabel8 = new javax.swing.JLabel();
        jCBCamiones = new javax.swing.JComboBox();
        jCHBAutoAsignacion = new javax.swing.JCheckBox();
        jLabel9 = new javax.swing.JLabel();
        jTFUser = new javax.swing.JTextField();
        jBGirarSentido = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jTFPeso = new javax.swing.JTextField();
        jBElimVia = new javax.swing.JButton();
        jTBElimInters = new javax.swing.JToggleButton();
        jBPrim = new javax.swing.JButton();
        jBKruskal = new javax.swing.JButton();
        jCheckBox1 = new javax.swing.JCheckBox();
        jBAgregarCamion = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jCBProdAbasto = new javax.swing.JComboBox();
        jLabel12 = new javax.swing.JLabel();
        jCBProdPed = new javax.swing.JComboBox();
        jBAgregarProdPedido = new javax.swing.JButton();
        jTFCantProdPed = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jTFCantProdAbasto = new javax.swing.JTextField();
        jBAgregarProdAbasto = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        areaDeDibujo1.setBackground(new java.awt.Color(254, 254, 254));
        areaDeDibujo1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                areaDeDibujo1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout areaDeDibujo1Layout = new javax.swing.GroupLayout(areaDeDibujo1);
        areaDeDibujo1.setLayout(areaDeDibujo1Layout);
        areaDeDibujo1Layout.setHorizontalGroup(
            areaDeDibujo1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 743, Short.MAX_VALUE)
        );
        areaDeDibujo1Layout.setVerticalGroup(
            areaDeDibujo1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jLabel1.setText("Intersección Inicial");

        jLabel2.setText("Intersección Final");

        jBCrearVia.setText("Crear Via");
        jBCrearVia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBCrearViaActionPerformed(evt);
            }
        });

        jLabel3.setText("Crear con Click :");

        jCBCrearAlClick.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Interseccion", "Casa", "Puesto" }));

        jLabel4.setText("Casa");

        jCBCasas.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jCBCasasItemStateChanged(evt);
            }
        });

        jBHacerPedido.setText("Hacer Pedido");
        jBHacerPedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBHacerPedidoActionPerformed(evt);
            }
        });

        jLabel5.setText("Via");

        jCBVias.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jCBViasItemStateChanged(evt);
            }
        });

        jLabel6.setText("Sentido");

        jCBSentido.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Simple", "Doble", "Bloqueada" }));
        jCBSentido.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jCBSentidoItemStateChanged(evt);
            }
        });

        jLabel7.setText("Puestos de Comida Rap");

        jCBPuesto.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jCBPuestoItemStateChanged(evt);
            }
        });

        jLabel8.setText("Camiones");

        jCHBAutoAsignacion.setText("Nombres Asignados Automaticamente");

        jLabel9.setText("Usuario");

        jTFUser.setEditable(false);
        jTFUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTFUserActionPerformed(evt);
            }
        });

        jBGirarSentido.setText("Girar Sentido");
        jBGirarSentido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBGirarSentidoActionPerformed(evt);
            }
        });

        jLabel10.setText("Peso");

        jTFPeso.setEditable(false);

        jBElimVia.setText("Eliminar Via");
        jBElimVia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBElimViaActionPerformed(evt);
            }
        });

        jTBElimInters.setText("Eliminar Inters.");
        jTBElimInters.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTBElimIntersActionPerformed(evt);
            }
        });

        jBPrim.setText("Prim");
        jBPrim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBPrimActionPerformed(evt);
            }
        });

        jBKruskal.setText("Kruskal");

        jCheckBox1.setText("Pintar Ruta Domicilio");
        jCheckBox1.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jCheckBox1ItemStateChanged(evt);
            }
        });

        jBAgregarCamion.setText("Agregar Camion");
        jBAgregarCamion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBAgregarCamionActionPerformed(evt);
            }
        });

        jLabel11.setText("Abasto Productos");

        jLabel12.setText("Lista Productos Pedido");

        jBAgregarProdPedido.setText("Agregar Producto");
        jBAgregarProdPedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBAgregarProdPedidoActionPerformed(evt);
            }
        });

        jTFCantProdPed.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTFCantProdPedActionPerformed(evt);
            }
        });

        jLabel13.setText("Cantidad");

        jLabel14.setText("Cantidad");

        jBAgregarProdAbasto.setText("Agregar Producto");

        jMenu1.setText("File");

        jMenuItem5.setText("Abrir Mapa");
        jMenu1.add(jMenuItem5);

        jMenuItem1.setText("Guardar Mapa");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuItem2.setText("Salir");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");

        jMenuItem3.setText("jMenuItem3");
        jMenu2.add(jMenuItem3);

        jMenuItem4.setText("jMenuItem4");
        jMenu2.add(jMenuItem4);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jCHBAutoAsignacion)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6)
                            .addComponent(jCheckBox1)
                            .addComponent(jLabel4)
                            .addComponent(jLabel9)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jCBCasas, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jTFUser, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jBHacerPedido, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jBAgregarProdPedido, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jCBProdPed, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel12, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(jLabel13)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jTFCantProdPed)))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel10)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                                    .addComponent(jTFPeso, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(jBElimVia, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jBGirarSentido, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jCBSentido, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jCBVias, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(39, 39, 39)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(jLabel14)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jTFCantProdAbasto))
                                    .addComponent(jCBProdAbasto, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(jBPrim, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jBKruskal, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel8)
                                            .addComponent(jCBCamiones, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jBAgregarCamion, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel11))
                                        .addGap(0, 3, Short.MAX_VALUE))
                                    .addComponent(jBAgregarProdAbasto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(38, 38, 38)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jCBPuesto, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(38, 38, 38)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jCBInterseccionFinal, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jCBInterseccionInicial, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jLabel2)
                                            .addComponent(jBCrearVia, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jTBElimInters, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)
                        .addComponent(areaDeDibujo1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(81, 81, 81)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jCBCrearAlClick, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(jLabel7))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jCBCasas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jCBPuesto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(jLabel9))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jTFUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel12)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jCBProdPed, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jTFCantProdPed, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel13))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jBAgregarProdPedido)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jBHacerPedido)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jCheckBox1)
                                .addGap(6, 6, 6))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jCBCamiones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jBAgregarCamion)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 2, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jBKruskal))
                                    .addComponent(jBPrim, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel11)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jCBProdAbasto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel14)
                                    .addComponent(jTFCantProdAbasto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jBAgregarProdAbasto)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jCBInterseccionInicial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jCBInterseccionFinal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jBCrearVia)
                                .addGap(58, 58, 58))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jCBVias, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jCBSentido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jBGirarSentido)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel10)
                                        .addGap(1, 1, 1)
                                        .addComponent(jTBElimInters))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jTFPeso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(2, 2, 2)
                                        .addComponent(jBElimVia)))))
                        .addGap(45, 45, 45)
                        .addComponent(jCHBAutoAsignacion)
                        .addGap(35, 35, 35))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jCBCrearAlClick, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(areaDeDibujo1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void areaDeDibujo1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_areaDeDibujo1MouseClicked
        String accion = jCBCrearAlClick.getSelectedItem().toString();
        String nombre;
        String elemento = jCBCrearAlClick.getSelectedItem().toString();
        if (!jCHBAutoAsignacion.isSelected()) {
            nombre = JOptionPane.showInputDialog("Nombre :" + elemento);
        } else {
            nombre = elemento + "-" + (mapaCiudad.listaIntersecciones.size() + 1);
        }
        if (nombre != null) {
            if (accion.equals("Interseccion")) {
                mapaCiudad.crearInterseccion(nombre, evt.getX(), evt.getY());
            } else if (accion.equals("Casa")) {
                mapaCiudad.crearCasa(evt.getX(), evt.getY());
                llenarComboBoxCasas();
            } else if (accion.equals("Puesto")) {
                mapaCiudad.crearPuesto(evt.getX(), evt.getY());
                llenarComboBoxPuestos();
            }
            llenarComboBoxIntersecciones();
        }
    }//GEN-LAST:event_areaDeDibujo1MouseClicked

    private void jBCrearViaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBCrearViaActionPerformed
        Object nombreInterseccionInicial = jCBInterseccionInicial.getSelectedItem();
        Object nombreInterseccionFinal = jCBInterseccionFinal.getSelectedItem();
        if (nombreInterseccionInicial != null && nombreInterseccionFinal != null && nombreInterseccionInicial != nombreInterseccionFinal) {
            String pesoStr = JOptionPane.showInputDialog("Distancia : ");
            if (pesoStr != null) {
                int peso = Integer.parseInt(pesoStr);
                mapaCiudad.crearVia(nombreInterseccionInicial.toString(), nombreInterseccionFinal.toString(), "Simple", peso);
                jTFPeso.setText(pesoStr);
                llenarComboBoxVias();
            }
        } else {
            JOptionPane.showMessageDialog(this, "No hay Intersecciones seleccionadas");
        }
    }//GEN-LAST:event_jBCrearViaActionPerformed

    private void jBHacerPedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBHacerPedidoActionPerformed
        Object ubiCasa = jCBCasas.getSelectedItem();

        if (ubiCasa != null) {
            String ubicacionCasa = ubiCasa.toString();
            String nombreUsuario = jTFUser.getText();
            if (nombreUsuario != null && !nombreUsuario.isEmpty()) {
                if (!mapaCiudad.solicitudPedido(ubicacionCasa)) {
                    JOptionPane.showMessageDialog(this, "Servicio no disponible en el momento.");
                }
            } else {
                String nombreUser = JOptionPane.showInputDialog("Nombre :");
                String telefonoUser = JOptionPane.showInputDialog("Teléfono :");
                String direccionUser = JOptionPane.showInputDialog("Dirección");
                Usuario nuevoUsuario = new Usuario(nombreUser, direccionUser, telefonoUser);
                if (mapaCiudad.registrarUsuario(ubicacionCasa, nuevoUsuario)) {
                    jTFUser.setText(nombreUser);
                }
            }
        } else {
            JOptionPane.showMessageDialog(this, "No está ninguna Casa Seleccionada");
        }
    }//GEN-LAST:event_jBHacerPedidoActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        almacen.almacenar(mapaCiudad);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jCBSentidoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jCBSentidoItemStateChanged
        if (evt.getStateChange() == ItemEvent.SELECTED) {
            String sentido = evt.getItem().toString();
            String nombreVia = jCBVias.getSelectedItem().toString();
            mapaCiudad.cambiarSentidoVia(nombreVia, sentido);
            System.out.println("Cambiando Sentido ");
            mapaCiudad.imprimirMapaCiudad();
        }
    }//GEN-LAST:event_jCBSentidoItemStateChanged

    private void jCBViasItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jCBViasItemStateChanged
        if (evt.getStateChange() == ItemEvent.SELECTED) {
            String nombreVia = jCBVias.getSelectedItem().toString();
            Via via = mapaCiudad.getVia(nombreVia);
            jCBSentido.setSelectedItem(via.getSentido());
            jTFPeso.setText(via.getDistancia() + "");
        }
    }//GEN-LAST:event_jCBViasItemStateChanged

    private void jTFUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTFUserActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTFUserActionPerformed

    private void jCBCasasItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jCBCasasItemStateChanged
        if (evt.getStateChange() == ItemEvent.SELECTED) {
            String ubicacionCasa = jCBCasas.getSelectedItem().toString();
            CasaParticular casa = mapaCiudad.getCasa(ubicacionCasa);
            String nombreUser = "";
            if (casa.getUser() != null) {
                nombreUser = casa.getUser().getNombre();
            }
            jTFUser.setText(nombreUser);
        }
    }//GEN-LAST:event_jCBCasasItemStateChanged

    private void jBGirarSentidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBGirarSentidoActionPerformed
        String nombreVia = jCBVias.getSelectedItem().toString();
        mapaCiudad.girarSentidoVia(nombreVia);
        jCBVias.setSelectedItem(nombreVia);
        System.out.println("Girando ");
        mapaCiudad.imprimirMapaCiudad();
    }//GEN-LAST:event_jBGirarSentidoActionPerformed

    private void jBElimViaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBElimViaActionPerformed
        Object objVia = jCBVias.getSelectedItem();
        if (objVia != null) {
            String nombreVia = objVia.toString();
            if (mapaCiudad.eliminarVia(nombreVia)) {
                JOptionPane.showMessageDialog(this, "Via " + nombreVia + " Eliminada con éxito");
                llenarComboBoxVias();
            }
        } else {
            JOptionPane.showMessageDialog(this, "No hay ninguna Via seleccionada");
        }

    }//GEN-LAST:event_jBElimViaActionPerformed

    private void jTBElimIntersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTBElimIntersActionPerformed
        Object objIntersInicial = jCBInterseccionInicial.getSelectedItem();
        if (objIntersInicial != null) {
            String nombreInterseccionInicial = objIntersInicial.toString();
            mapaCiudad.eliminarInterseccion(nombreInterseccionInicial);
            llenarComboBoxVias();
            llenarComboBoxCasas();
            llenarComboBoxIntersecciones();
        } else {
            JOptionPane.showMessageDialog(this, "No hay ninguna Intersección seleccionada");
        }
    }//GEN-LAST:event_jTBElimIntersActionPerformed

    private void jBPrimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBPrimActionPerformed

    }//GEN-LAST:event_jBPrimActionPerformed

    private void jCheckBox1ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jCheckBox1ItemStateChanged
        boolean seleccionado = false;
        if (evt.getStateChange() == ItemEvent.SELECTED) {
            seleccionado = true;
        } else if (evt.getStateChange() == ItemEvent.DESELECTED) {
            seleccionado = false;
        }
        areaDeDibujo1.setPintarRutaDomicilio(seleccionado);
    }//GEN-LAST:event_jCheckBox1ItemStateChanged

    private void jBAgregarCamionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBAgregarCamionActionPerformed
        Object objPuesto = jCBPuesto.getSelectedItem();
        if (objPuesto != null) {
            String nombrePuesto = objPuesto.toString();
            LinkedList<PuestoComidaRapida> listaPuestos = mapaCiudad.listaPuestos;
            for (PuestoComidaRapida puesto : listaPuestos) {
                if (puesto.getNombre().equals(nombrePuesto)) {
                    String nombre = "";
                    if (!jCHBAutoAsignacion.isSelected()) {
                        nombre = JOptionPane.showInputDialog("Nombre Camión : ");
                    } else {
                        nombre = "CM" + (puesto.getListaCamiones().size() + 1);
                    }
                    String velStr = JOptionPane.showInputDialog(this, "Velocidad : ");
                    String capStr = JOptionPane.showInputDialog(this, "Capacidad : ");
                    Camion camion = new Camion(nombre, puesto.getPosX(), puesto.getPosY() + 15, 20, 20, Integer.parseInt(velStr), Integer.parseInt(capStr));
                    puesto.agregarCamion(camion);
                    jCBCamiones.addItem(camion.getNombre());
                    break;
                }
            }
        } else {
            JOptionPane.showMessageDialog(this, "No hay ningún Puesto Seleccionado");
        }
    }//GEN-LAST:event_jBAgregarCamionActionPerformed

    private void jCBPuestoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jCBPuestoItemStateChanged
        Object objPuesto = jCBPuesto.getSelectedItem();
        if (objPuesto != null) {
            String nombrePuesto = objPuesto.toString();
            LinkedList<PuestoComidaRapida> listaPuestos = mapaCiudad.listaPuestos;
            jCBCamiones.removeAllItems();
            for (PuestoComidaRapida puesto : listaPuestos) {
                if (puesto.getNombre().equals(nombrePuesto)) {
                    LinkedList<Camion> listaCamiones = puesto.getListaCamiones();
                    for (Camion camion : listaCamiones) {
                        jCBCamiones.addItem(camion.getNombre());
                    }
                    break;
                }
            }
        }
    }//GEN-LAST:event_jCBPuestoItemStateChanged

    private void jTFCantProdPedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTFCantProdPedActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTFCantProdPedActionPerformed

    private void jBAgregarProdPedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBAgregarProdPedidoActionPerformed
        Object objCasa = jCBCasas.getSelectedItem();
        if (objCasa != null) {
            String nombreCasa = objCasa.toString();
            LinkedList<CasaParticular> listaCasas = mapaCiudad.listaCasas;
            for (CasaParticular casa : listaCasas) {
                if (casa.getNombre().equals(nombreCasa)) {
                    Usuario user = casa.getUser();
                    if (user != null) {
                        int confirmación = 0;
                        while (confirmación == 0) {
                            String nombreProd = JOptionPane.showInputDialog("Nombre Producto :");
                            //String precioProd = JOptionPane.showInputDialog("Quiere agregar otro producto ?");
                            String cantidadProd = JOptionPane.showInputDialog("Cantidad :");
                            user.agregarProductoAlPedido(new Producto(nombreProd, 10, Integer.parseInt(cantidadProd)));
                            jCBProdPed.addItem(nombreProd);
                            confirmación = JOptionPane.showConfirmDialog(null, "Quiere agregar otro producto ?");                       
                        }
                    } else {
                        JOptionPane.showMessageDialog(this, "Registre Usuario");
                    }
                    break;
                }
            }
        }
    }//GEN-LAST:event_jBAgregarProdPedidoActionPerformed
    public void llenarComboBoxIntersecciones() {
        LinkedList<Nodo> listaIntersecciones = mapaCiudad.listaIntersecciones;
        jCBInterseccionInicial.removeAllItems();
        jCBInterseccionFinal.removeAllItems();
        for (Nodo inters : listaIntersecciones) {
            jCBInterseccionInicial.addItem(inters.getNombre());
            jCBInterseccionFinal.addItem(inters.getNombre());
        }
    }

    public void llenarComboBoxCasas() {
        LinkedList<CasaParticular> listaCasas = mapaCiudad.getCasas();
        jCBCasas.removeAllItems();
        for (CasaParticular casa : listaCasas) {
            jCBCasas.addItem(casa.getNombre());
        }
    }

    public void llenarComboBoxPuestos() {
        LinkedList<PuestoComidaRapida> listaCasas = mapaCiudad.listaPuestos;
        jCBPuesto.removeAllItems();
        for (PuestoComidaRapida puesto : listaCasas) {
            jCBPuesto.addItem(puesto.getNombre());
            LinkedList<Camion> listaCamiones = puesto.getListaCamiones();
            jCBCamiones.removeAllItems();
            for (Camion camion : listaCamiones) {
                jCBCamiones.addItem(camion.getNombre());
            }
        }
    }

    public void llenarComboBoxVias() {
        LinkedList<Via> listaVias = mapaCiudad.getVias();
        jCBVias.removeAllItems();
        jTFPeso.setText("");
        for (Via via : listaVias) {
            jCBVias.addItem(via.getNombre());
            jCBSentido.setSelectedItem(via.getSentido());
            jTFPeso.setText(via.getDistancia() + "");
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipalBocadito.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipalBocadito.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipalBocadito.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipalBocadito.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaPrincipalBocadito().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private bocaditos.AreaDeDibujo areaDeDibujo1;
    private javax.swing.JButton jBAgregarCamion;
    private javax.swing.JButton jBAgregarProdAbasto;
    private javax.swing.JButton jBAgregarProdPedido;
    private javax.swing.JButton jBCrearVia;
    private javax.swing.JButton jBElimVia;
    private javax.swing.JButton jBGirarSentido;
    private javax.swing.JButton jBHacerPedido;
    private javax.swing.JButton jBKruskal;
    private javax.swing.JButton jBPrim;
    private javax.swing.JComboBox jCBCamiones;
    private javax.swing.JComboBox jCBCasas;
    private javax.swing.JComboBox jCBCrearAlClick;
    private javax.swing.JComboBox jCBInterseccionFinal;
    private javax.swing.JComboBox jCBInterseccionInicial;
    private javax.swing.JComboBox jCBProdAbasto;
    private javax.swing.JComboBox jCBProdPed;
    private javax.swing.JComboBox jCBPuesto;
    private javax.swing.JComboBox jCBSentido;
    private javax.swing.JComboBox jCBVias;
    private javax.swing.JCheckBox jCHBAutoAsignacion;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JToggleButton jTBElimInters;
    private javax.swing.JTextField jTFCantProdAbasto;
    private javax.swing.JTextField jTFCantProdPed;
    private javax.swing.JTextField jTFPeso;
    private javax.swing.JTextField jTFUser;
    // End of variables declaration//GEN-END:variables
}
